## Specifies whether resources from this chart should be installed
enabled: true

deployment:
  image:
    repository: gcr.io/timatal1-198022/app-blacklist
    tag: latest
  replicaCount: 1
  resources:
    limits:
      cpu: 150m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  environment:
    PORT: 8080
    DB_NAME: app_blacklist
